### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by zuurw** [wxinll/music-163#1]
Hello @wxinll, Im a Graphic Designer that likes to contribute to open source projects, can you tell me more about music-123? I like very much music projects, so if you want it will be a pleasure to me to design a logo for music-123.

If you want just tell me what you want for the logo?

Greetings

**Comment by wxinll** [comment]
Sorry, I didn't see this message before. I am a newcomer learning JavaScript and this project is just used for practice. So I think it is not necessary to add the design element .Design is cool! Thanks very much for your kindness. Hope more person get help from you!

**Comment by zuurw** [comment]
Ok.
Greetings!
